version: "3"

networks:
  gitea:
    external: false

services:

  # ========================================
  #          GIT.MICHAELLISANO.COM
  # ========================================

  gitea-server:
    image: gitea/gitea:1.19.3
    container_name: gitea
    environment:
      USER_UID: 1000
      USER_GID: 1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"

  gitea-cloudflared:
    container_name: cloudflared-gitea
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run --url http://server:3000
    environment:
      - TUNNEL_TOKEN=${GITEA_TUNNEL_TOKEN}
    networks:
      - gitea


